POST http://ovz6.n-solenii2016.n03kn.vps.myjino.ru:49319/auth
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nickname"

John Doe
--WebAppBoundary
Content-Disposition: form-data; name="password"

123456
--WebAppBoundary--

###

POST http://ovz6.n-solenii2016.n03kn.vps.myjino.ru:49319/auth
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nickname"

John Doe
--WebAppBoundary
Content-Disposition: form-data; name="password"

12345
--WebAppBoundary--

###

POST http://ovz6.n-solenii2016.n03kn.vps.myjino.ru:49319/test
Accept: */*
Cache-Control: no-cache

###
