PUT http://ovz6.n-solenii2016.n03kn.vps.myjino.ru:49319/signin
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nickname"

Sindy Sanders
--WebAppBoundary
Content-Disposition: form-data; name="password"

12345678910
--WebAppBoundary--

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200 || response.status === 201, "Error " + response.status);
    });
%}
###
PUT http://ovz6.n-solenii2016.n03kn.vps.myjino.ru:49319/signin
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nickname"

Gendo Ikari
--WebAppBoundary
Content-Disposition: form-data; name="password"

getintotherobot
--WebAppBoundary--

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200 || response.status === 201, "Error " + response.status);
    });
%}
###
PUT http://ovz6.n-solenii2016.n03kn.vps.myjino.ru:49319/signin
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nickname"

William Shakespeare
--WebAppBoundary
Content-Disposition: form-data; name="password"

asdfghjk
--WebAppBoundary--

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200 || response.status === 201, "Error " + response.status);
    });
%}
###
PUT http://ovz6.n-solenii2016.n03kn.vps.myjino.ru:49319/signin
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nickname"

Luis Kerrol
--WebAppBoundary
Content-Disposition: form-data; name="password"

kjhgfds
--WebAppBoundary--

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200 || response.status === 201, "Error " + response.status);
    });
%}
###
PUT http://ovz6.n-solenii2016.n03kn.vps.myjino.ru:49319/signin
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nickname"

Standford University
--WebAppBoundary
Content-Disposition: form-data; name="password"

university
--WebAppBoundary--

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200 || response.status === 201, "Error " + response.status);
    });
%}
###
PUT http://ovz6.n-solenii2016.n03kn.vps.myjino.ru:49319/signin
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nickname"

Jo Johnson
--WebAppBoundary
Content-Disposition: form-data; name="password"

jo
--WebAppBoundary--

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200 || response.status === 201, "Error " + response.status);
    });
%}
###

PUT http://ovz6.n-solenii2016.n03kn.vps.myjino.ru:49319/signin
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nickname"

John Doe
--WebAppBoundary
Content-Disposition: form-data; name="password"

12345
--WebAppBoundary--

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200 || response.status === 201, "Error " + response.status);
    });
%}
###

PUT http://ovz6.n-solenii2016.n03kn.vps.myjino.ru:49319/signin
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nickname"

Lyel Lipton
--WebAppBoundary
Content-Disposition: form-data; name="password"

12345
--WebAppBoundary--

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200 || response.status === 201, "Error " + response.status);
    });
%}
###

PUT http://ovz6.n-solenii2016.n03kn.vps.myjino.ru:49319/signin
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nickname"

Senator Armstrong
--WebAppBoundary
Content-Disposition: form-data; name="password"

jack
--WebAppBoundary--

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200 || response.status === 201, "Error " + response.status);
    });
%}
###

PUT http://ovz6.n-solenii2016.n03kn.vps.myjino.ru:49319/signin
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nickname"

Gordon Ramsy
--WebAppBoundary
Content-Disposition: form-data; name="password"

actuallygoodfood
--WebAppBoundary--

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200 || response.status === 201, "Error " + response.status);
    });
%}
###

PUT http://ovz6.n-solenii2016.n03kn.vps.myjino.ru:49319/signin
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nickname"

User
--WebAppBoundary
Content-Disposition: form-data; name="password"

user
--WebAppBoundary--

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200 || response.status === 201, "Error " + response.status);
    });
%}
###
