POST http://ovz6.n-solenii2016.n03kn.vps.myjino.ru:49319/auth
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nickname"

Jo Johnson
--WebAppBoundary
Content-Disposition: form-data; name="password"

jo
--WebAppBoundary--

###

PUT http://ovz6.n-solenii2016.n03kn.vps.myjino.ru:49319/recipes/create
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="recipe_img"

< ./img/WaterPouringGlass_iS1172707826-1.jpg
--WebAppBoundary
Content-Disposition: form-data; name="recipe_hashtag"

simple
--WebAppBoundary
Content-Disposition: form-data; name="recipe_hashtag"

transparent
--WebAppBoundary
Content-Disposition: form-data; name="recipe_title"

A glass of water
--WebAppBoundary
Content-Disposition: form-data; name="recipe_description"

A glass of the purest clear water
--WebAppBoundary
Content-Disposition: form-data; name="recipe_step_1"

Fill empty glass with water from decanter or water tap.
--WebAppBoundary
Content-Disposition: form-data; name="recipe_step_2"

Enjoy the rest of your day!
--WebAppBoundary--

###

PUT http://ovz6.n-solenii2016.n03kn.vps.myjino.ru:49319/recipes/create
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="recipe_hashtag"

bakery
--WebAppBoundary
Content-Disposition: form-data; name="recipe_title"

Bread
--WebAppBoundary
Content-Disposition: form-data; name="recipe_description"

>(^o^)<
--WebAppBoundary
Content-Disposition: form-data; name="recipe_step_1"

Give flover
--WebAppBoundary
Content-Disposition: form-data; name="recipe_step_2"

bake it in water of glass
--WebAppBoundary
Content-Disposition: form-data; name="recipe_step_3"

Seems, it doesent work
--WebAppBoundary--

###
